// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlockUI: typeof import('primevue/blockui')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LocationCU: typeof import('./src/views/location/LocationCU.vue')['default']
    LocationRD: typeof import('./src/views/location/LocationRD.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Paginator: typeof import('primevue/paginator')['default']
    PortalLocationCU: typeof import('./src/views/location/PortalLocationCU.vue')['default']
    PortalLocationRD: typeof import('./src/views/location/PortalLocationRD.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecretaryConductorChanges: typeof import('./src/views/shift-tablet-crew/secretary-report/SecretaryConductorChanges.vue')['default']
    SecretaryCrew: typeof import('./src/views/shift-tablet-crew/secretary-report/SecretaryCrew.vue')['default']
    SecretaryReportDescription: typeof import('./src/views/shift-tablet-crew/secretary-report/SecretaryReportDescription.vue')['default']
    SecretaryReviewProblems: typeof import('./src/views/shift-tablet-crew/secretary-report/SecretaryReviewProblems.vue')['default']
    SecretarySteps: typeof import('./src/views/shift-tablet-crew/secretary-report/SecretarySteps.vue')['default']
    ShiftDefinitionCU: typeof import('./src/views/shift-definition/ShiftDefinitionCU.vue')['default']
    ShiftDefinitionRD: typeof import('./src/views/shift-definition/ShiftDefinitionRD.vue')['default']
    ShiftDefinitionTemplate: typeof import('./src/views/shift-definition/ShiftDefinitionTemplate.vue')['default']
    ShiftTabletCrewAgentReplacement: typeof import('./src/views/shift-tablet-crew/coordinator/ShiftTabletCrewAgentReplacement.vue')['default']
    ShiftTabletCrewCreate: typeof import('./src/views/shift-tablet-crew/coordinator/ShiftTabletCrewCreate.vue')['default']
    ShiftTabletCrewRD: typeof import('./src/views/shift-tablet-crew/ShiftTabletCrewRD.vue')['default']
    ShiftTabletCU: typeof import('./src/views/shift-tablet/ShiftTabletCU.vue')['default']
    ShiftTabletRD: typeof import('./src/views/shift-tablet/ShiftTabletRD.vue')['default']
    Steps: typeof import('primevue/steps')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
