// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShiftDefinitionCU: typeof import('./src/views/shift-definition/ShiftDefinitionCU.vue')['default']
    ShiftDefinitionRD: typeof import('./src/views/shift-definition/ShiftDefinitionRD.vue')['default']
    ShiftLocationCU: typeof import('./src/views/shift-location/ShiftLocationCU.vue')['default']
    ShiftLocationRD: typeof import('./src/views/shift-location/ShiftLocationRD.vue')['default']
    ShiftProductionTypeCU: typeof import('./src/views/shift-production-type/ShiftProductionTypeCU.vue')['default']
    ShiftProductionTypeRD: typeof import('./src/views/shift-production-type/ShiftProductionTypeRD.vue')['default']
    ShiftTabletCrewCU: typeof import('./src/views/shift-tablet-crew/ShiftTabletCrewCU.vue')['default']
    ShiftTabletCrewRD: typeof import('./src/views/shift-tablet-crew/ShiftTabletCrewRD.vue')['default']
    ShiftTabletCrewView: typeof import('./src/views/ShiftTabletCrewView.vue')['default']
    ShiftTabletCU: typeof import('./src/views/shift-tablet/ShiftTabletCU.vue')['default']
    ShiftTabletRD: typeof import('./src/views/shift-tablet/ShiftTabletRD.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}

export {}
